# Generated by Django 3.0b1 on 2020-04-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('name_zh', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default='unspecified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name_zh', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default='unspecified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name_zh', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default='unspecified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name_zh', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default='unspecified', max_length=128)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('name_zh', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default='unspecified', max_length=64)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Program')),
            ],
        ),
    ]
