# Generated by Django 3.0b1 on 2020-04-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_comment_course_ftp_schedule_thumbsdown_thumbsup'),
        ('basic', '0002_classroom_department_faculty_major_program'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name_zh', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name_en', models.CharField(default='unspecified', max_length=64)),
                ('avatar_url', models.TextField(default='', null=True)),
                ('position', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('office_room', models.TextField(default='', null=True)),
                ('office_hour', models.TextField(default='', null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='TeachCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
