# ALL API
OK = 0  # 正常
WARNING = 1 # 警告（一般可忽略）

AUTH_SIGN_VERIFICATION_FAILED = -1001  # sign 验证失败
AUTH_TIME_INVALID = -1002  # 请求已过期
AUTH_TOKEN_INVALID = -1003  # token 无效


# DELETE /course/comments
COURSE_COMMENT_ID_NOT_FOUND = -4000 # 未找到课程评论ID

# POST /course/comments
COURSE_ID_NOT_FOUNT = -4001 # 未找到课程ID
COURSE_COMMENT_CONTENT_ILLEGAL = -4002 # 要评论的内容无效（非法评论内容）
COURSE_COMMENT_CONTENT_TOO_LONG = -4003 # 评论内容太长
COURSE_COMMENT_CONTENT_EMPTY = -4004 # 评论内容不能为空

# GET /course/comments
COURSE_ID_NOT_FOUNT = COURSE_ID_NOT_FOUNT
COURSE_RECORD_FROM_INVALID = -4005 # 从第from条开始获取，from参数无效

# GET /course/ftp
COURSE_FTP_ID_NOT_FOUNT = -4006 # 课程ID未找到

# POST /course/ftp
COURSE_FTP_ID_NOT_FOUNT = COURSE_FTP_ID_NOT_FOUNT
COURSE_FTP_HOST_ILLEGAL = -4007 # FTP 主机名非法
COURSE_FTP_USERNAME_ILLEGAL = -4008 # FTP 用户名非法
COURSE_FTP_PASSWORD_ILLEGAL = -4009 # FTP 密码非法

# GET /teacher
TEACHER_ID_NOT_FOUNT = -5000 # 未找到教师ID

# POST /my/profile
PROFILE_NICKNAME_ILLEGAL = -6000 # 昵称非法
PROFILE_SIGNATURE_ILLEGAL = -6001 # 个性签名非法
PROFILE_AVATAR_INVALID = -6002 # 头像URL不合法

# GET /my/timetable
TIMETABLE_SEMESTER_INVALID = -7000 # 学期无效
TIMETABLE_WEEK_INVALID = -7001 # 周数无效




OTHER_ARGUMENT_INVALID = -9000  # 其它类型参数错误
