LOGIN_URL = 'https://coes-stud.must.edu.mo/coes/login.do'
STUDENTINFO_URL = 'https://coes-stud.must.edu.mo/coes/StudentInfo.do'
STUDYPLANGROUP_URL = 'https://coes-stud.must.edu.mo/coes/StudyPlanGroup.do'
LOGOUT_URL = 'https://coes-stud.must.edu.mo/coes/logout.do'
TABLETIME_URL = 'https://coes-stud.must.edu.mo/coes/AcademicRecordsForm.do'