LOGIN_URL = 'https://coes-stud.must.edu.mo/coes/login.do'
STUDENT_INFO_URL = 'https://coes-stud.must.edu.mo/coes/StudentInfo.do'
STUDY_PLAN_GROUP_URL = 'https://coes-stud.must.edu.mo/coes/StudyPlanGroup.do'
LOGOUT_URL = 'https://coes-stud.must.edu.mo/coes/logout.do'
TIME_TABLE_URL = 'https://coes-stud.must.edu.mo/coes/AcademicRecordsForm.do'