# Generated by Django 3.0b1 on 2020-04-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_comment_course_ftp_schedule_thumbsdown_thumbsup'),
        ('basic', '0002_classroom_department_faculty_major_program'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name_zh', models.CharField(max_length=16, null=True)),
                ('name_en', models.CharField(max_length=16, null=True)),
                ('nickname', models.CharField(max_length=64, null=True)),
                ('sign', models.CharField(max_length=256, null=True)),
                ('gender', models.BooleanField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('birthplace', models.TextField(null=True)),
                ('nationality', models.TextField(null=True)),
                ('avatar_url', models.TextField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=36)),
                ('coes_token', models.TextField()),
                ('coes_cookie', models.TextField(default='')),
                ('token_expired_time', models.DateTimeField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Faculty')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Major')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Program')),
            ],
        ),
        migrations.CreateModel(
            name='TakeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=16, null=True)),
                ('exam_datetime', models.DateTimeField(null=True)),
                ('exam_seat', models.CharField(max_length=16, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('exam_classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.ClassRoom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=15)),
                ('state', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
